#!/usr/bin/env bash

# Run this script to start UPPAAL

# Default options if needed.
# Add -Duppaal.extra if you want to force extra features.
# JAVA_DEF="-Duppaal.extra"
#JAVA_DEF=-Duppaal.lsc
#JAVA_DEF=

# Force language if LANG is defined.
if [ ! -z "$LANG" ]; then
  JAVA_DEF="$JAVA_DEF -Duser.language=${LANG/_*/}"
fi

# Fix splash option if no splash is asked (Java 6).
NOJAR=""
for opt in $* ; do
  if [ "$opt" = "--no-splash" ]; then
    JAVA_DEF="$JAVA_DEF -Duppaal.extra -splash:/dev/null"
    NOJAR="y"
    break
  fi
done

# Setup.
HERE=$(dirname "$(readlink -e $0)")
if [ "`uname -o`" = "Cygwin" ]; then
  HERE="${HERE/#\/cygdrive\//}"
  HERE="${HERE/\//:/}"
fi
JAR="$HERE/uppaal.jar"

if [[ "$DISPLAY" != ":"* ]]; then
    # No antialias if remote execution (better performance).
    EXTRADEF="-splash:/dev/null"
    EXTRAOPT="--no-antialias"
else
    # Add anti-aliasing and opengl acceleration by default:
    EXTRADEF="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dsun.java2d.opengl=true"
    EXTRAOPT=""
fi

# Start.
if [ -z "$NOJAR" ]; then
  java $JAVA_DEF $EXTRADEF -jar "$JAR" $EXTRAOPT "$@"
else
  java $JAVA_DEF $EXTRADEF -classpath "$JAR" com.uppaal.gui.Main $EXTRAOPT "$@"
fi
