#!/usr/bin/env bash

# Run this script to start UPPAAL

# Default options if needed.
# Add -Duppaal.extra if you want to force extra features.
# JAVA_DEF="-Duppaal.extra"
#JAVA_DEF=-Duppaal.lsc
#JAVA_DEF=

# Force language if LANG is defined.
if [ ! -z "$LANG" ]; then
  JAVA_DEF="$JAVA_DEF -Duser.language=${LANG/_*/}"
fi

# Setup.
HERE=$(dirname "$(readlink -e $0)")
JAR="$HERE/uppaal.jar"

if [[ "$DISPLAY" != ":"* ]]; then
    # No antialias if remote execution (better performance).
    EXTRAOPT="--no-antialias"
fi

# Start.
if [ -z "$NOJAR" ]; then
  exec java $JAVA_DEF $EXTRADEF -jar "$JAR" $EXTRAOPT "$@"
else
  exec java $JAVA_DEF $EXTRADEF -classpath "$JAR" UPPAAL $EXTRAOPT "$@"
fi
